from os import environ

TWILIO_ACCOUNT_SID = environ.get('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = environ.get('TWILIO_AUTH_TOKEN')
TWILIO_WHATSAPP_NUMBER = environ.get('TWILIO_WHATSAPP_NUMBER')
WEB3_PROVIDER_URL = environ.get('WEB3_PROVIDER_URL')
TEST_PHONE_NUMBER = environ.get('TEST_PHONE_NUMBER')
SECRET_KEY = environ.get('SECRET_KEY')
SERVER_NAME = environ.get('SERVER_NAME')